### ISSUE TITLE
[1434] Évaluation théorique de performance d’un système à antennes distribuées sur canaux multi-trajets partiellement bloqués

### ISSUE THREAD

**Issue by thibaut29** [GRETSI-2025/Label-Reproductible#5]
### Titre

Formule théorique de la probabilité d’erreur binaire d’un système MIMO distribué dans des canaux à multi-trajets partiellement bloqués

### Identifiant

ID1434

### Éléments reproductibles

```markdown
- Figure 1.
- Figure 2.
- Figure 3.
La figure 3 est générée à partir de valeurs de taux d'erreur binaire données directement pour gagner du temps. Cependant, le code permettant d'obtenir ces valeurs est également fourni.
```

### URL

https://gitlab.com/thibaut_29450/recherche_reproductible_gretsi25.git

### Langage

- [x] Python
- [ ] Matlab
- [ ] C
- [ ] C++
- [ ] Julia

### OS

- [x] Linux
- [ ] MacOS
- [x] Windows
- [ ] Autre

### Processeur(s)

Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz

### RAM

256 GB DDR4

### Carte(s) graphique(s)

nvidia RTX A5000

### Estimation du temps de compilation

quelques secondes

### Estimation du temps d'exécution

quelques minutes à quelques heures

### Informations complémentaires

```markdown
Les courbes ont été obtenues et testées avec plusieurs configurations matérielles, notamment avec et sans GPU. Le temps de simulation varie donc significativement. De plus, des paramètres tels que la taille du batch et le nombre d'itérations influencent grandement cette durée, comme expliqué dans le README du projet.

En revanche, la génération des figures illustratives (1 et 2) ne prend que quelques secondes.
```

**Comment by tomMoral** [comment]
Hello,

I started reviewing the code, it the first two scripts for the illustrative figures work well but I get some errors when trying to generate the data for the third figure. It seems that `sionna` has been updated.
Could the author adapt the code to work with the newest version of `sionna` or provide the version I should be using?

As a side note (not related to this reproducibility eval), I strongly advise the authors to use a linter to make their code more readable.
A very efficient and popular one is `ruff`, which can be installed with `pip install ruff` and will fix most linting error with simply `ruff format .`.

**Comment by thibaut29** [comment]
> Hello,
> 
> I started reviewing the code, it the first two scripts for the illustrative figures work well but I get some errors when trying to generate the data for the third figure. It seems that `sionna` has been updated. Could the author adapt the code to work with the newest version of `sionna` or provide the version I should be using?
> 
> As a side note (not related to this reproducibility eval), I strongly advise the authors to use a linter to make their code more readable. A very efficient and popular one is `ruff`, which can be installed with `pip install ruff` and will fix most linting error with simply `ruff format .`.

Hello, @tomMoral , 
Thank you for pointing that out! I've committed the fix — the issue was due to target_ber no longer being a valid parameter for the simulate function. Simply commenting out line 590 solves the problem.

Also, I wasn’t aware of ruff, but I’ll definitely look into it soon — thanks for the suggestion!

**Comment by tomMoral** [comment]
Hello,

Thanks a lot for the quick fix but there is still an issue.
The error I get is the following:

```
Traceback (most recent call last):
  File "/XXX/main_Peb_and_MonteCarlo_simulation_DMIMO.py", line 559, in <module>
    model_distributed_MIMO = DistributedMIMOModel(num_ofdm_symbols = SIMULATION_PARAM["num_ofdm_symbols"],
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXX/main_Peb_and_MonteCarlo_simulation_DMIMO.py", line 178, in __init__
    self.ue_array = sionna.channel.tr38901.AntennaArray(
                    ^^^^^^^^^^^^^^
  File "/XXX/miniconda/envs/gretsi/lib/python3.12/site-packages/sionna/__init__.py", line 14, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module sionna has no attribute channel
```

From what I see in the `sionna` module, there seem to have a module `sionna.phy.channel` which seem compatible?

**Comment by thibaut29** [comment]
> Hello,
> 
> Thanks a lot for the quick fix but there is still an issue. The error I get is the following:
> 
> ```
> Traceback (most recent call last):
>   File "/XXX/main_Peb_and_MonteCarlo_simulation_DMIMO.py", line 559, in <module>
>     model_distributed_MIMO = DistributedMIMOModel(num_ofdm_symbols = SIMULATION_PARAM["num_ofdm_symbols"],
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/XXX/main_Peb_and_MonteCarlo_simulation_DMIMO.py", line 178, in __init__
>     self.ue_array = sionna.channel.tr38901.AntennaArray(
>                     ^^^^^^^^^^^^^^
>   File "/XXX/miniconda/envs/gretsi/lib/python3.12/site-packages/sionna/__init__.py", line 14, in __getattr__
>     raise AttributeError(f"module {__name__} has no attribute {name}")
> AttributeError: module sionna has no attribute channel
> ```
> 
> From what I see in the `sionna` module, there seem to have a module `sionna.phy.channel` which seem compatible?

Hello,

Thanks for the detailed error message!
I actually fixed the issue yesterday, but the code is currently compatible with Sionna version 1.0.2, which is the latest release working with Python 3.10.16.

The simplest solution for now is to create a virtual environment with Python 3.10.16 and then install Sionna 1.0.2 using:

```
conda create -n compat_sionna python=3.10 -y
conda activate compat_sionna
pip install sionna==1.0.2

```
I’ll update the README shortly to clarify the required versions and avoid further confusion.

Sorry for the inconvenience, and thanks again for your patience!

**Comment by tomMoral** [comment]
Hello,

I still get the same error after calling the following lines:

```bash
mamba create -n gretsi python=3.10
mamba activate gretsi
pip install sionna==1.0.2
python main_Peb_and_MonteCarlo_simulation_DMIMO.py 
```

Could you try recreating an environment to check if you get the same error?
It feels like the easier would be to adapt the code to this version of `sionna`, which simply add `phy.` before `channel` no?

**Comment by thibaut29** [comment]
> Hello,
> 
> I still get the same error after calling the following lines:
> 
> mamba create -n gretsi python=3.10
> mamba activate gretsi
> pip install sionna==1.0.2
> python main_Peb_and_MonteCarlo_simulation_DMIMO.py 
> Could you try recreating an environment to check if you get the same error? It feels like the easier would be to adapt the code to this version of `sionna`, which simply add `phy.` before `channel` no?

Hello,

After deeper checks, I realized the issue was on my side:  
Even though I had installed Sionna 1.0.2, I was still using the wrong environment in Spyder, leading me to test the code against an older Sionna version by mistake.

I have now properly activated the correct environment (Python 3.10 + Sionna 1.0.2), and updated the code accordingly:
- The updated Sionna structure requires using `sionna.phy.channel` instead of `sionna.channel`.
- I also modified the calls to Block classes (such as `ApplyOFDMChannel`, `Demapper`, etc.) to pass arguments individually instead of passing them as a list, as required by the new Sionna API.

Everything now runs correctly with a clean environment, and I have pushed the corrected version.

Thanks again for your patience and for your helpful feedback!

Best regards,  
Thibaut

**Comment by tomMoral** [comment]
Hello,

I ran the code and reproduced one of the curves from figure 3. Thanks for your effort!

Looking at `generate_figure3.py`, I see that the values for the curves are hard-coded in the file, which seems like a bad practice and doesn't allow for the figure to be regenerated from scratch.
A better practice would be to save the curve generated from `main_Peb_and_MonteCarlo_simulation_DMIMO.py` in a CSV file and create the figure from these CSV. 
That way, the code is reproducible as you can generate the figure from the CSV and the CSV from the script.

Could you update the repo to allow for this?

**Comment by thibaut29** [comment]
Hello,

Thanks for the helpful suggestion!

You're absolutely right — storing the results in CSV files and regenerating the figure from those would improve reproducibility and clarity. I will update the repository accordingly:
- `main_Peb_and_MonteCarlo_simulation_DMIMO.py` will export the Monte Carlo and theoretical BER curves to CSV.
- `generate_figure3.py` will then simply load these CSVs to produce the figure.

That said, `generate_figure3.py` was initially meant just as a shortcut to quickly replot the figure without rerunning the whole simulation each time — but I agree that having it based on external result files is a much better practice.

Thanks again for the feedback!

Best regards,  
Thibaut

**Comment by thibaut29** [comment]
> Hello,
> 
> I ran the code and reproduced one of the curves from figure 3. Thanks for your effort!
> 
> Looking at `generate_figure3.py`, I see that the values for the curves are hard-coded in the file, which seems like a bad practice and doesn't allow for the figure to be regenerated from scratch. A better practice would be to save the curve generated from `main_Peb_and_MonteCarlo_simulation_DMIMO.py` in a CSV file and create the figure from these CSV. That way, the code is reproducible as you can generate the figure from the CSV and the CSV from the script.
> 
> Could you update the repo to allow for this?

Work done

**Comment by tomMoral** [comment]
Hello!

I can confirm that I was able to reproduce figure 3 from the script (execution time 25min on a NVIDIA A40).
Thanks a lot for improving the code! :)

![Image](https://github.com/user-attachments/assets/24df7e27-cb0d-4184-8336-0a5862703d32)

Maybe a few last advice:
- I ran this code on a cluster with no X-server, adding a `plt.savefig` at the end of the script to save the figure in pdf would probably make it easier to get the figure (but this I could manage 😄 )
- The code is not super easy to read for `main_Peb_and_*.py`, maybe splitting the file and moving the model definition to another file would make it easier to see the code organisation. But overall, this is nitpicks, so no need to update the submission with it, ofc.

Best
Thomas
